### ISSUE TITLE
Page numbers?

### ISSUE THREAD

**Issue by reagle** [kangni/ibooks_notes_exporter#4]
Thank you for this! However, it doesn't appear to export the page numbers that the highlights and notes appear on...?

**Comment by kangni** [comment]
@reagle I'll support this feature ASAP.

**Comment by reagle** [comment]
On 6/18/20 3:20 AM, kangni wrote:
> @reagle <https://github.com/reagle> I'll support this feature ASAP.

This might interest you:

https://github.com/Galarius/pinotate/issues/2#event-3456648851

I can see you not wanting to support it given the page numbers are not fixed.

**Comment by kangni** [comment]
> On 6/18/20 3:20 AM, kangni wrote: @reagle <[@reagle](https://github.com/reagle)> I'll support this feature ASAP.
> This might interest you: [Galarius/pinotate#2 (comment)](https://github.com/Galarius/pinotate/issues/2#event-3456648851) I can see you not wanting to support it given the page numbers are not fixed.

Aha, I noticed that, when resizing the interface the page numbers will change. the PDF makes more sense with the page numbers.

Although it's still a demo and exporting text is rather ugly, I'll be using my spare time to tackle some of the features I thought of earlier to make the tool more user friendly.

If you have any other questions about export, feel free to click New issue. 😄
